In [ ]:
2 + 3

5

In [ ]:
import numpy as np


In [ ]:
sales = [0, 5, 155, 0, 518, 1826, 616, 53]
sales_array = np.array(sales)
type(sales_array)

numpy.ndarray

NumPy arrays have these key properties:


1.   ndim – the number of dimensions (axes) in the array.
2.   shape – the size of the array for each dimension.
3. size – the total number of elements in the array.
4.  dtype – the data type of the elements in the array.

In [ ]:
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"size: {sales_array.size}")
print(f"dtype: {sales_array.dtype}")

ndim: 1
shape: (8,)
size: 8
dtype: int64


In [ ]:
sales = [[0, 5, 155, 0, 518], [9, 5, 8, 4, 5]] # two dimension with each 5 elements
sales_array = np.array(sales)
print(f"shape: {sales_array.shape}")

shape: (2, 5)


In [ ]:
my_list = [x * 10 for x in range(1, 11)]

my_list = np.array(my_list)
print(my_list)
print(type(my_list))

[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


In [ ]:
txt = """
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"size: {sales_array.size}")
print(f"dtype: {sales_array.dtype}")"""

print(txt.replace('sales_array', 'my_list'))


print(f"ndim: {my_list.ndim}")
print(f"shape: {my_list.shape}")
print(f"size: {my_list.size}")
print(f"dtype: {my_list.dtype}")


In [ ]:
print(f"ndim: {my_list.ndim}")
print(f"shape: {my_list.shape}")
print(f"size: {my_list.size}")
print(f"dtype: {my_list.dtype}")

ndim: 1
shape: (10,)
size: 10
dtype: int64


# ARRAY CREATION
- As an alternative to converting lists, you can create arrays using functions

1. **ones**: Creates an array of ones of a given size, as float by default.
   
    ***np.ones((rows, cols), dtype)***

2. **zeros**: Creates an array of zeros of a given size, as float by default.

    ***np.zeros((rows, cols), dtype)***

3. **arrange**: Creates an array of integers with given start & stop values, and a step size (only stop is required, and is not inclusive).

    ***np.arange(start, stop, step)***

4. **linspace**: Creates an array of floats with given start & stop values with n elements, separated by a consistent step size (stop is inclusive).
    ***np.linspace(start, stop, n)***

5. **reshape**: Changes an array into the specified dimensions, if compatible.
    ***np.array.reshape(rows, cols)***


In [ ]:
np.ones(4,)

array([1., 1., 1., 1.])

In [ ]:
np.zeros((2, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10, 1)

array([5, 6, 7, 8, 9])

In [ ]:
np.linspace(10, 100, 50) # n elements i.e, 50

array([ 10.        ,  11.83673469,  13.67346939,  15.51020408,
        17.34693878,  19.18367347,  21.02040816,  22.85714286,
        24.69387755,  26.53061224,  28.36734694,  30.20408163,
        32.04081633,  33.87755102,  35.71428571,  37.55102041,
        39.3877551 ,  41.2244898 ,  43.06122449,  44.89795918,
        46.73469388,  48.57142857,  50.40816327,  52.24489796,
        54.08163265,  55.91836735,  57.75510204,  59.59183673,
        61.42857143,  63.26530612,  65.10204082,  66.93877551,
        68.7755102 ,  70.6122449 ,  72.44897959,  74.28571429,
        76.12244898,  77.95918367,  79.79591837,  81.63265306,
        83.46938776,  85.30612245,  87.14285714,  88.97959184,
        90.81632653,  92.65306122,  94.48979592,  96.32653061,
        98.16326531, 100.        ])

In [ ]:
np.arange(1, 9, 2).reshape(2,2)

array([[1, 3],
       [5, 7]])

In [ ]:
from numpy.random import default_rng

rng = default_rng(12345)

random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [ ]:
my_array = np.linspace(10, 100, 10).reshape(5,2)
my_array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [ ]:
rng = default_rng(221)
random_arrray = rng.random(9).reshape(3, 3)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

# Indexing & slicing
**one-dimensional arrays is the same as base Python**

• array[index] – indexing to access a single element (0-indexed)

• array[start:stop:step size] – slicing to access a series of elements (stop is not inclusive)

**two-dimensional arrays requires an extra index or slice**

• array[row index, column index] – indexing to access a single element (0-indexed)

• array[start:stop:step size, start:stop:step size] – slicing to access a series of elements


In [ ]:
import numpy as np

product_2d = np.array([[1, 2, 3, 4, 5, 6], [10, 20, 30, 40, 50, 60]])

product_2d

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [ ]:
product_2d [1,1]

20

In [ ]:
product_2d[:, ::-1]

array([[ 6,  5,  4,  3,  2,  1],
       [60, 50, 40, 30, 20, 10]])

In [ ]:
from numpy import random

dummy_array = random.rand(5, 3)

In [ ]:
dummy_array.reshape(3, 5)

array([[0.52875251, 0.84645086, 0.31875322, 0.77880808, 0.69390245],
       [0.37306604, 0.22446698, 0.7653808 , 0.59059949, 0.40144888],
       [0.75162882, 0.84104015, 0.8202002 , 0.1231533 , 0.4208318 ]])

In [ ]:
dummy_array

array([[0.52875251, 0.84645086, 0.31875322],
       [0.77880808, 0.69390245, 0.37306604],
       [0.22446698, 0.7653808 , 0.59059949],
       [0.40144888, 0.75162882, 0.84104015],
       [0.8202002 , 0.1231533 , 0.4208318 ]])

In [ ]:
dummy_array[:2, :] # first two rows

array([[0.52875251, 0.84645086, 0.31875322],
       [0.77880808, 0.69390245, 0.37306604]])

In [ ]:
dummy_array[:, 0] # first column

array([0.52875251, 0.77880808, 0.22446698, 0.40144888, 0.8202002 ])

In [ ]:
dummy_array[2,1]

0.7653807960105885

# ARRAY OPERATIONS



In [ ]:
sales = [[0, 5, 155,0, 518], [0, 1827, 616, 317, 325]]

sales_array = np.array(sales)

sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [ ]:
sales_array + 2 # adds 2 to every element

array([[   2,    7,  157,    2,  520],
       [   2, 1829,  618,  319,  327]])

In [ ]:
quantity = sales_array[0,:] #first row of sales_array
price = sales_array[1,:] # second row of sales_array

quantity * price

array([     0,   9135,  95480,      0, 168350])

In [ ]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

total = prices * 5

total

array([ 29.95,  34.95, 112.45, 499.95,  24.95, 249.95])

In [ ]:
discount_pct = random.rand(6)
print(discount_pct)

pct_owed = 1-discount_pct
print(pct_owed)

final_owed = total * pct_owed
print(final_owed.round(2))

[0.56586082 0.30437754 0.71515255 0.53929629 0.26813817 0.18381717]
[0.43413918 0.69562246 0.28484745 0.46070371 0.73186183 0.81618283]
[ 13.    24.31  32.03 230.33  18.26 204.  ]


# FILTERING ARRAYS

You can filter arrays by indexing them with a logical test

• Only the array elements in positions where the logical test returns True are returned

In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [ ]:
sales_array != 0 # checks the element is not zero

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

In [ ]:
sales_array [sales_array != 0] # returns the value which are TRUE

array([   5,  155,  518, 1827,  616,  317,  325])

You can filter arrays with multiple logical tests

• Use | for or conditions and & for and conditions


In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [ ]:
sales_array[(sales_array == 616) | (sales_array < 100)]
 # this retuns an array with elements equal to 616 or less than 100


array([  0,   5,   0,   0, 616])

In [ ]:
sales_array[(sales_array > 100) & (sales_array < 500)]
# This returns an array with elements greater than 100 and less than 500

array([155, 317, 325])

In [ ]:
mask = (sales_array > 100) & (sales_array < 500) # we can store complex filtering in variable
sales_array[mask]

array([155, 317, 325])

You can filter arrays based on values in other arrays

• Use the Boolean array returned from the other array to index the array you want to filter

In [ ]:
quantity

array([  0,   5, 155,   0, 518])

In [ ]:
price

array([   0, 1827,  616,  317,  325])

In [ ]:
quantity[price < 500] # returns elements in quantity where price is less than 500

array([  0,   0, 518])

#Modifying Array values
You can modify array values by assigning new ones

In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [ ]:
sales_array[0, 0] = 1 # This assigns new value

sales_array

array([[   1,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [ ]:
sales_array[sales_array == 0] = 5

sales_array

array([[   1,    5,  155,    5,  518],
       [   5, 1827,  616,  317,  325]])

#WHERE FUNCTION

The **where()** NumPy function performs a logical test and returns a given value if the test is True, or another if the test is False

***np.where(logical test, value if True, value if False)***

In [ ]:
inventory_array = np.array([12, 102, 18, 0, 0])
inventory_array

array([ 12, 102,  18,   0,   0])

In [ ]:
product_array = np.array(['fruits', 'veg', 'cer', 'dai', 'egg'], dtype='<U10')
product_array

array(['fruits', 'veg', 'cer', 'dai', 'egg'], dtype='<U10')

In [ ]:
np.where(inventory_array <= 0, 'Out of Stock', 'In Stock')


array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [ ]:
np.where(inventory_array <= 0, 'Out of stock', product_array)

array(['fruits', 'veg', 'cer', 'Out of stock', 'Out of stock'],
      dtype='<U12')

In [ ]:
products = np.array(['rare tomato', 'gourmet ice cream'], dtype='<U20')
products.dtype

dtype('<U20')

In [ ]:
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

# Array Aggregation methods

Array aggregation methods let you calcualte metrics like sum, mean and max

- array.sum()
- array.max()
- array.mean()
- array.min()

In [ ]:
import numpy as np
sales = [[0, 5, 155,0, 518], [0, 1827, 616, 317, 325]]

sales_array = np.array(sales)

sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [ ]:
sales_array.sum()

3763

In [ ]:
sales_array.max()

1827

You can also aggregate across rows or columns

In [ ]:
sales_array.sum(axis= 0) # Aggregates across rows

array([   0, 1832,  771,  317,  843])

In [ ]:
sales_array.sum(axis = 1) # Aggregates across columns

array([ 678, 3085])

#Array Functions
Array functions let you perform other aggregations like median and percentiles

- np.median(array)

- np.percentile(array, n)

- np.unique(array)

- np.sqrt(array)

In [ ]:
np.median(sales_array)

236.0

In [ ]:
np.unique(sales_array)

array([   0,    5,  155,  317,  325,  518,  616, 1827])

In [ ]:
np.sqrt(sales_array)

array([[ 0.        ,  2.23606798, 12.4498996 ,  0.        , 22.75961335],
       [ 0.        , 42.74342055, 24.81934729, 17.80449381, 18.02775638]])

# Sorting Arrays

The sort() method will sort arrays in place.

- Use the axis argument to specift the dimension to sort by

- axis = 1 by defalut, row by row

In [ ]:
sales_array.sort()
sales_array

array([[   0,    0,    5,  155,  518],
       [   0,  317,  325,  616, 1827]])

In [ ]:
sales_array.sort(axis=0)
sales_array

array([[   0,    0,    5,  155,  518],
       [   0,  317,  325,  616, 1827]])

# Vectorization

It is the process of pushing array operations into optimized C code, which is easier and more efficient than writing for loops.

# Broadcasting

It lets you perform vectorized operations with arrays of different sizes, where NumPy will expand the smaller array to fit the larger one.

- single values (scalars) can be broadcast into arrays of any dimensions. ie., [1]

In [3]:
import numpy as np

# Create two NumPy arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Element-wise addition using vectorization
result = a + b

print(result)  # Output: [ 6  8 10 12]

[ 6  8 10 12]


In [1]:
import numpy as np

test_array = np.array([[1, 2, 3], [1, 2,  3], [1, 2, 3]])

test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [2]:
test_array + 1

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

- dimensions with a length greater than one must be the same size

In [4]:
test_array + np.array([3, 2, 1])

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [5]:
test_array + np.array([3, 2, 1]).reshape(3, 1) # added vertically

array([[4, 5, 6],
       [3, 4, 5],
       [2, 3, 4]])

In [6]:
test_array + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [7]:
test_array[0, :] + test_array[:, 1].reshape(3, 1)

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [8]:
np.ones((2, 3, 3)) + np.ones(3,)

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])