In [ ]:
2 + 3

5

In [ ]:
import numpy as np


In [ ]:
sales = [0, 5, 155, 0, 518, 1826, 616, 53]
sales_array = np.array(sales)
type(sales_array)

numpy.ndarray

NumPy arrays have these key properties:


1.   ndim – the number of dimensions (axes) in the array.
2.   shape – the size of the array for each dimension.
3. size – the total number of elements in the array.
4.  dtype – the data type of the elements in the array.

In [ ]:
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"size: {sales_array.size}")
print(f"dtype: {sales_array.dtype}")

ndim: 1
shape: (8,)
size: 8
dtype: int64


In [ ]:
sales = [[0, 5, 155, 0, 518], [9, 5, 8, 4, 5]] # two dimension with each 5 elements
sales_array = np.array(sales)
print(f"shape: {sales_array.shape}")

shape: (2, 5)


In [ ]:
my_list = [x * 10 for x in range(1, 11)]

my_list = np.array(my_list)
print(my_list)
print(type(my_list))

[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


In [ ]:
txt = """
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"size: {sales_array.size}")
print(f"dtype: {sales_array.dtype}")"""

print(txt.replace('sales_array', 'my_list'))


print(f"ndim: {my_list.ndim}")
print(f"shape: {my_list.shape}")
print(f"size: {my_list.size}")
print(f"dtype: {my_list.dtype}")


In [ ]:
print(f"ndim: {my_list.ndim}")
print(f"shape: {my_list.shape}")
print(f"size: {my_list.size}")
print(f"dtype: {my_list.dtype}")

ndim: 1
shape: (10,)
size: 10
dtype: int64


# ARRAY CREATION
- As an alternative to converting lists, you can create arrays using functions

1. **ones**: Creates an array of ones of a given size, as float by default.
   
    ***np.ones((rows, cols), dtype)***

2. **zeros**: Creates an array of zeros of a given size, as float by default.

    ***np.zeros((rows, cols), dtype)***

3. **arrange**: Creates an array of integers with given start & stop values, and a step size (only stop is required, and is not inclusive).

    ***np.arange(start, stop, step)***

4. **linspace**: Creates an array of floats with given start & stop values with n elements, separated by a consistent step size (stop is inclusive).
    ***np.linspace(start, stop, n)***

5. **reshape**: Changes an array into the specified dimensions, if compatible.
    ***np.array.reshape(rows, cols)***


In [ ]:
np.ones(4,)

array([1., 1., 1., 1.])

In [ ]:
np.zeros((2, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10, 1)

array([5, 6, 7, 8, 9])

In [ ]:
np.linspace(10, 100, 50) # n elements i.e, 50

array([ 10.        ,  11.83673469,  13.67346939,  15.51020408,
        17.34693878,  19.18367347,  21.02040816,  22.85714286,
        24.69387755,  26.53061224,  28.36734694,  30.20408163,
        32.04081633,  33.87755102,  35.71428571,  37.55102041,
        39.3877551 ,  41.2244898 ,  43.06122449,  44.89795918,
        46.73469388,  48.57142857,  50.40816327,  52.24489796,
        54.08163265,  55.91836735,  57.75510204,  59.59183673,
        61.42857143,  63.26530612,  65.10204082,  66.93877551,
        68.7755102 ,  70.6122449 ,  72.44897959,  74.28571429,
        76.12244898,  77.95918367,  79.79591837,  81.63265306,
        83.46938776,  85.30612245,  87.14285714,  88.97959184,
        90.81632653,  92.65306122,  94.48979592,  96.32653061,
        98.16326531, 100.        ])

In [ ]:
np.arange(1, 9, 2).reshape(2,2)

array([[1, 3],
       [5, 7]])

In [ ]:
from numpy.random import default_rng

rng = default_rng(12345)

random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [ ]:
my_array = np.linspace(10, 100, 10).reshape(5,2)
my_array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [ ]:
rng = default_rng(221)
random_arrray = rng.random(9).reshape(3, 3)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

# Indexing & slicing
**one-dimensional arrays is the same as base Python**

• array[index] – indexing to access a single element (0-indexed)

• array[start:stop:step size] – slicing to access a series of elements (stop is not inclusive)

**two-dimensional arrays requires an extra index or slice**

• array[row index, column index] – indexing to access a single element (0-indexed)

• array[start:stop:step size, start:stop:step size] – slicing to access a series of elements


In [11]:
import numpy as np

product_2d = np.array([[1, 2, 3, 4, 5, 6], [10, 20, 30, 40, 50, 60]])

product_2d

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [12]:
product_2d [1,1]

20